on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.1
      - name: cache node modules
        uses: actions/cache@v4.3.0
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: install pnpm
        uses: https://github.com/pnpm/action-setup@v4.2.0
        with:
          version: 10.15.1
          run_install: true
      - name: run tests
        run: pnpm test
